export const comparisonCurrency = "GBP";

export const tripComparisonData = [
  {
    id: "lisbon",
    slug: "lisbon-portugal",
    city: "Lisbon",
    country: "Portugal",
    duration: 7,
    totalCost: 1325,
    dailyCost: 189,
    flightCost: 245,
    accommodationCost: 560,
    foodCost: 245,
    transportCost: 70,
    activitiesCost: 205,
    budgetStatus: "Within budget",
    budgetType: "success",
    interestMatch: 92,
    seasonSuitability: 90,
    overallScore: 91,
    travelStyle: "Culture and food",
    interests: ["Culture", "Food", "History"],
    highlights: [
      "Praca do Comercio",
      "Belem",
      "Jeronimos Monastery",
      "Sao Jorge Castle",
    ],
    recommendation:
      "Lisbon provides the strongest overall balance between budget, selected interests and seasonal suitability.",
  },
  {
    id: "prague",
    slug: "prague-czech-republic",
    city: "Prague",
    country: "Czech Republic",
    duration: 7,
    totalCost: 1150,
    dailyCost: 164,
    flightCost: 210,
    accommodationCost: 490,
    foodCost: 210,
    transportCost: 65,
    activitiesCost: 175,
    budgetStatus: "Within budget",
    budgetType: "success",
    interestMatch: 86,
    seasonSuitability: 88,
    overallScore: 87,
    travelStyle: "History and architecture",
    interests: ["History", "Culture", "Architecture"],
    highlights: [
      "Prague Castle",
      "Charles Bridge",
      "Old Town Square",
      "Petrin Hill",
    ],
    recommendation:
      "Prague offers a strong cultural experience with lower accommodation and daily costs.",
  },
  {
    id: "budapest",
    slug: "budapest-hungary",
    city: "Budapest",
    country: "Hungary",
    duration: 7,
    totalCost: 1085,
    dailyCost: 155,
    flightCost: 190,
    accommodationCost: 455,
    foodCost: 205,
    transportCost: 60,
    activitiesCost: 175,
    budgetStatus: "Best value",
    budgetType: "primary",
    interestMatch: 83,
    seasonSuitability: 84,
    overallScore: 84,
    travelStyle: "Value and sightseeing",
    interests: ["History", "Food", "Sightseeing"],
    highlights: [
      "Buda Castle",
      "Parliament Building",
      "Fishermans Bastion",
      "Central Market Hall",
    ],
    recommendation:
      "Budapest is the lowest-cost option and offers the best value for travellers prioritising budget.",
  },
];
