import {
  FaCalendarDays,
  FaCloudSun,
  FaLocationDot,
  FaMoon,
  FaSun,
  FaWandSparkles,
} from "react-icons/fa6";
import styles from "./itinerary.module.css";

const itineraryPeriods = [
  {
    key: "morning",
    label: "Morning",
    icon: <FaSun />,
  },
  {
    key: "afternoon",
    label: "Afternoon",
    icon: <FaCloudSun />,
  },
  {
    key: "evening",
    label: "Evening",
    icon: <FaMoon />,
  },
];

export default function ItineraryPreview({ itinerary }) {
  if (!itinerary) {
    return (
      <section className={styles.emptyItinerary} role="status">
        <span
          className={`${styles.emptyItineraryIcon} d-inline-flex align-items-center justify-content-center`}
        >
          <FaCalendarDays />
        </span>

        <p className={styles.emptyItineraryLabel}>Itinerary preview</p>

        <h2 className={styles.emptyItineraryTitle}>
          Your day-by-day plan will appear here
        </h2>

        <p className={styles.emptyItineraryText}>
          Complete the Trip Planner and select Generate itinerary to create a
          personalised travel schedule.
        </p>
      </section>
    );
  }

  const itineraryDays = Array.isArray(itinerary.days) ? itinerary.days : [];

  return (
    <section className={`card ${styles.itineraryPreviewCard}`}>
      <div className={styles.previewAccent} />

      <div className="card-body p-4 p-lg-5">
        <div className="d-flex flex-column flex-lg-row justify-content-between align-items-lg-start gap-4 mb-4">
          <div>
            <span className={styles.itineraryBadge}>
              <FaWandSparkles />
              AI-generated itinerary
            </span>

            <h2 className={styles.itineraryTitle}>
              <FaLocationDot />
              {itinerary.destination}
            </h2>

            <p className={styles.itinerarySummaryText}>{itinerary.summary}</p>
          </div>

          <div className={styles.itineraryDayCount}>
            <p className={styles.dayCountLabel}>Total itinerary days</p>

            <p className={styles.dayCountValue}>{itineraryDays.length}</p>

            <p className={styles.dayCountText}>Structured travel days</p>
          </div>
        </div>

        {itineraryDays.length === 0 ? (
          <div className={styles.warningPanel} role="alert">
            The generated itinerary does not contain any travel days.
          </div>
        ) : (
          <div className="row g-4">
            {itineraryDays.map((day) => (
              <div className="col-12" key={day.day}>
                <article className={styles.dayCard}>
                  <div className={styles.dayHeader}>
                    <div className="d-flex align-items-center gap-3">
                      <span className={styles.dayNumber}>
                        {String(day.day).padStart(2, "0")}
                      </span>

                      <div>
                        <p className={styles.dayLabel}>Day {day.day}</p>

                        <h3 className={styles.dayTitle}>{day.title}</h3>
                      </div>
                    </div>

                    <span
                      className={`${styles.dayCalendarIcon} d-inline-flex align-items-center justify-content-center`}
                    >
                      <FaCalendarDays />
                    </span>
                  </div>

                  <div className="row g-3">
                    {itineraryPeriods.map((period) => (
                      <div
                        className="col-12 col-lg-4"
                        key={`${day.day}-${period.key}`}
                      >
                        <div className={styles.periodCard}>
                          <span
                            className={`${styles.periodIcon} d-inline-flex align-items-center justify-content-center`}
                          >
                            {period.icon}
                          </span>

                          <div>
                            <p className={styles.periodLabel}>{period.label}</p>

                            <p className={styles.periodText}>
                              {day[period.key]}
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </article>
              </div>
            ))}
          </div>
        )}

        <div className={styles.aiNotice}>
          <FaCloudSun />

          <p>
            This itinerary was generated by TravelMind AI. Review the
            activities, request changes where needed and save the final version
            to your account.
          </p>
        </div>
      </div>
    </section>
  );
}
