import { FaCalendarDays, FaCloudSun, FaLocationDot } from "react-icons/fa6";

export default function ItineraryPreview({ itinerary }) {
  if (!itinerary) {
    return (
      <div className="alert alert-light border mb-0" role="status">
        No itinerary has been generated yet.
      </div>
    );
  }

  const itineraryDays = Array.isArray(itinerary.days) ? itinerary.days : [];

  return (
    <section className="card border-0 shadow-sm">
      <div className="card-body p-4 p-lg-5">
        <div className="d-flex flex-column flex-lg-row justify-content-between align-items-lg-start gap-3 mb-4">
          <div>
            <span className="badge bg-dark mb-3">AI-generated itinerary</span>

            <h2 className="h3 fw-bold text-dark mb-2">
              <FaLocationDot className="me-2" />
              {itinerary.destination}
            </h2>

            <p className="text-secondary mb-0">{itinerary.summary}</p>
          </div>

          <div className="text-lg-end">
            <p className="text-secondary small mb-1">Total itinerary days</p>

            <p className="h4 fw-bold text-dark mb-0">{itineraryDays.length}</p>
          </div>
        </div>

        {itineraryDays.length === 0 ? (
          <div className="alert alert-warning mb-0" role="alert">
            The generated itinerary does not contain any days.
          </div>
        ) : (
          <div className="row g-4">
            {itineraryDays.map((day) => (
              <div className="col-12" key={day.day}>
                <article className="card border h-100">
                  <div className="card-header bg-white border-bottom p-4">
                    <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2">
                      <div>
                        <p className="text-primary fw-semibold mb-1">
                          Day {day.day}
                        </p>

                        <h3 className="h5 fw-bold text-dark mb-0">
                          {day.title}
                        </h3>
                      </div>

                      <FaCalendarDays
                        className="fs-4 text-secondary"
                        aria-hidden="true"
                      />
                    </div>
                  </div>

                  <div className="card-body p-4">
                    <div className="row g-3">
                      <div className="col-12 col-lg-4">
                        <div className="h-100 border rounded-3 p-3">
                          <p className="fw-bold text-dark mb-2">Morning</p>

                          <p className="text-secondary mb-0">{day.morning}</p>
                        </div>
                      </div>

                      <div className="col-12 col-lg-4">
                        <div className="h-100 border rounded-3 p-3">
                          <p className="fw-bold text-dark mb-2">Afternoon</p>

                          <p className="text-secondary mb-0">{day.afternoon}</p>
                        </div>
                      </div>

                      <div className="col-12 col-lg-4">
                        <div className="h-100 border rounded-3 p-3">
                          <p className="fw-bold text-dark mb-2">Evening</p>

                          <p className="text-secondary mb-0">{day.evening}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
              </div>
            ))}
          </div>
        )}

        <div className="alert alert-primary d-flex align-items-start gap-3 mt-4 mb-0">
          <FaCloudSun className="fs-5 mt-1" aria-hidden="true" />

          <p className="mb-0">
            This itinerary was generated by TravelMind AI and can be refined
            before it is saved.
          </p>
        </div>
      </div>
    </section>
  );
}
